# Generated by Django 4.2.6 on 2023-10-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerimage',
            name='extracted_text',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
